### ISSUE TITLE
Incorrect Version 

### ISSUE THREAD

**Issue by iallenmathew** [ph453-z3r0/Among_Us#1]
![Screenshot 2024-09-23 203436](https://github.com/user-attachments/assets/f908e231-93c4-4a88-b9dd-4d9cbba8b7f7)

I'm unable to play Among Us on PC because it says my version is outdated.
I've tried restarting the game and my computer, but the issue persists.

**Comment by ph453-z3r0** [comment]
Hi... I am sorry that you are facing an issue, 
The error occurred cause the room created was using **_Among Us 2024.4.2_** (latest version), but the game file I provided was **_Among Us 2024.3.5m_**. 
_**[*]**_ The error message is shown as in the latest version, Among Us added **_new ROLES_**, which would not be right now in the game file I provided...

_Thank you for posting this issue,_

- [**_!_**]  I'll find a way to update the game file and let you know shortly... Still, you can try out other public rooms hosted on older versions! Enjoy your gameplay !!

**_[Thank you for trying out my file !!]_**

**Comment by iallenmathew** [comment]
Just let me know if you need any help! I would love to contribute to this project in case if you need any assistance! 
**Thank You!**

**Comment by ph453-z3r0** [comment]
> Just let me know if you need any help! I would love to contribute to this project in case if you need any assistance! **Thank You!**

It would be appreciated !!! 
You can contact me directly: ph453.z3r0@gmail.com

**Comment by iallenmathew** [comment]
Hey, I got the latest version game files. Just ping me once you are free so that I can share it with you!

**Comment by ph453-z3r0** [comment]
> Great, let's look into the game files!

**Comment by ph453-z3r0** [comment]
May I know where you got the files if you don't mind? I just now checked
your repository
